project_id = "tczettddxmlcmhdhgebw"

[functions.get-fixtures]
verify_jwt = false

[functions.get-match-details]
verify_jwt = false

[functions.league-stats]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.create-portal-session]
verify_jwt = false

[functions.update-prediction-results]
verify_jwt = false
 
 [functions.generate-ai-predictions]
 verify_jwt = false

[functions.revenuecat-webhook]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.check-goals]
verify_jwt = false

[functions.send-win-push]
verify_jwt = false

[functions.test-push]
verify_jwt = false