project_id = "tczettddxmlcmhdhgebw"

[functions.get-fixtures]
verify_jwt = false

[functions.get-match-details]
verify_jwt = false

[functions.league-stats]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false